[package]
name = "spryteo-svg"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "SceneGraph to SVG emission, optimizer, metadata sidecar."

[dependencies]
spryteo-core = { path = "../spryteo-core", version = "0.0.2" }
spryteo-geom = { path = "../spryteo-geom", version = "0.0.2" }
serde.workspace = true
thiserror.workspace = true
