version: '{build}'

image: Ubuntu2204

environment:
  CARGO_TERM_COLOR: always

cache:
  - $HOME/.cargo/registry -> Cargo.lock
  - target -> Cargo.lock

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt clippy
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - rustc --version
  - cargo --version

build_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo fmt --all -- --check
  - cargo clippy --workspace --all-targets -- -D warnings
  - cargo build --workspace --all-targets

test_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo test --workspace --release
  - wasm-pack build bindings/wasm --target web --release
  - test $(gzip -c bindings/wasm/pkg/spryteo_wasm_bg.wasm | wc -c) -lt 819200
