/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function convertSync(bytes: Buffer, optionsJson?: string | undefined | null): any
export declare function convert(bytes: Buffer, optionsJson?: string | undefined | null): Promise<any>
