/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The explicitly blocking API. Runs the whole conversion on the calling
 * JavaScript thread; use [`convert`] unless you want that.
 */
export declare function convertSync(bytes: Buffer, optionsJson?: string | undefined | null): any
/**
 * Convert off the JavaScript event loop, returning a Promise.
 *
 * Concurrency is bounded by libuv's thread pool (4 threads by default,
 * set with `UV_THREADPOOL_SIZE`). Conversions beyond that queue rather
 * than oversubscribing the CPU.
 */
export declare function convert(bytes: Buffer, optionsJson?: string | undefined | null): Promise<unknown>
